In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf


### Tensorflow Tensor

In [2]:
import tensorflow as tf
a=tf.constant(2)
b=tf.constant(5)
x=tf.Variable(3)
x.assign(4)
y=a*x+b
print(y)


tf.Tensor(13, shape=(), dtype=int32)


In [3]:

import tensorflow.compat.v1 as tf
a = tf.constant(5) #todo: define a tf tensor
b = tf.constant(3)  # Define tensors
tf.disable_v2_behavior()
tf.disable_eager_execution()
x=tf.placeholder(dtype=tf.int32)
y=a* x + b
with tf.Session() as ss:
    result=ss.run(y,feed_dict={x:3})
    print(result)
    





18


### Tensorflow Placeholders

**Placeholders (tf.placeholder):**
These were used as inputs to the graph where the values would be provided at runtime via feed_dict. 

They allowed dynamic input feeding during the execution of the graph.

**Session:** In TensorFlow 1.x, you needed to create a tf.Session() to run operations, and placeholders required you to feed values into them during session execution.

**TensorFlow 2.x:** Focuses on constants (tf.constant) and variables (tf.Variable). 

Eager execution removes the need for placeholders or sessions.

**TensorFlow 1.x:** Used placeholders (tf.placeholder) for feeding data into graphs at runtime and required sessions to execute the graph.

### Tensorflow: Tensor Operations

In [2]:
import tensorflow as tf
a=tf.constant([1,2,3])
b=tf.constant([2,3,4])
sum_result = tf.add(a,b)  # Addition
diff_result = tf.subtract(a,b) # Subtraction
quot_result = tf.divide(a,b) # Division
prod_result = tf.multiply(a,b) # Multiplication

print("Sum of Tensors",sum_result)
print("Difference of tensors",diff_result)
print("Quotient of Tensor",quot_result)
print("Product of tensors ",prod_result)



Sum of Tensors tf.Tensor([3 5 7], shape=(3,), dtype=int32)
Difference of tensors tf.Tensor([-1 -1 -1], shape=(3,), dtype=int32)
Quotient of Tensor tf.Tensor([0.5        0.66666667 0.75      ], shape=(3,), dtype=float64)
Product of tensors  tf.Tensor([ 2  6 12], shape=(3,), dtype=int32)


In [3]:
# Element-wise operations
min_result = tf.minimum(a, b)
max_result = tf.maximum(a, b)
abs_result = tf.abs(a)

print("Minimum:", min_result)
print("Maximum:", max_result)
print("Absolute value:", abs_result)


Minimum: tf.Tensor([1 2 3], shape=(3,), dtype=int32)
Maximum: tf.Tensor([2 3 4], shape=(3,), dtype=int32)
Absolute value: tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [13]:
# Cast the tensor `a` to float32 to match the type of 1e-8


# Now you can safely compute the logarithm
#log_result = tf.math.log(tf.maximum(a,b))  # Ensure positive values for logarithm
exp_result = tf.exp(a)


#print("Logarithm:", log_result)
print("Exponential:", exp_result)


Exponential: tf.Tensor([ 2.7182817  7.389056  20.085537 ], shape=(3,), dtype=float32)


In [19]:
a = tf.constant([3, 6, 3]) #todo: create a tensor

scalar = tf.constant(2) #todo: create a constant
broadcast_result = tf.multiply(a, scalar)
print("Broadcasted Addition:", broadcast_result)


Broadcasted Addition: tf.Tensor([ 6 12  6], shape=(3,), dtype=int32)


In [20]:
sum_axis = tf.reduce_max(a) # Sum across the first axis
mean_axis = tf.reduce_mean(a, axis=0)  # Mean across the second axis
print("Sum across axis 0:", sum_axis)
print("Mean across axis 0:", mean_axis)


Sum across axis 0: tf.Tensor(6, shape=(), dtype=int32)
Mean across axis 0: tf.Tensor(4, shape=(), dtype=int32)


#### Matmul example

In [22]:
import tensorflow as tf

# Example: Input data for a neural network layer
#todo: create input data tensor of shape (2,2), same for weights
input_data = tf.constant([[1,2],[3,4]])   # Shape: (2, 2)
weights =tf.constant([[2,3],[3,4]])    # Shape: (2, 2)

# Matrix multiplication between input and weights
output = tf.matmul(input_data, weights)
print("Neural Network Layer Output:\n", output)


Neural Network Layer Output:
 tf.Tensor(
[[ 8 11]
 [18 25]], shape=(2, 2), dtype=int32)


#### Multiply Example (Element Wise)

In [38]:
import tensorflow as tf

# Example: Simulating image pixel values
image = tf.constant([[255, 128], [64, 32]], dtype=tf.int32)  # Shape: (2, 2)

# Scaling factor for each pixel (element-wise multiplication)
#for example, you want to minimize the size of the image by halfw
scaling_factor = tf.constant(5)
scaled_image = tf.add(image, scaling_factor)
print("Scaled Image:\n", scaled_image)


Scaled Image:
 tf.Tensor(
[[260 133]
 [ 69  37]], shape=(2, 2), dtype=int32)


#### Multiply Example

In [40]:
import tensorflow as tf

# Example: Simulating a sequence of words (embeddings)
sequence = tf.constant([[1,2],[3,4],[2,3]])  # Shape: (2, 3)

# Attention scores (one for each word in the sequence)
attention_scores =tf.constant([[1,2],[3,4],[2,3]]) #Shape: (2, 3)

# Apply attention weights using element-wise multiplication
weighted_sequence = tf.multiply(sequence, attention_scores)
print("Weighted Sequence:\n", weighted_sequence)


Weighted Sequence:
 tf.Tensor(
[[ 1  4]
 [ 9 16]
 [ 4  9]], shape=(3, 2), dtype=int32)


#### Gradient Derivates

In [34]:
import tensorflow as tf
x=tf.Variable(2.0)
def f(x):
    y=x**2+2*x-5
    return y
with tf.GradientTape() as tape:
    y=f(x)
g=tape.gradient(y,x)
print(g)
    



tf.Tensor(6.0, shape=(), dtype=float32)


### Tensorflow: Tensor vs Numpy Ndarray
Let's do some benchmarking

In [ ]:
import time
import numpy as np
import tensorflow as tf

# Create large random matrices
size = 10000
np_matrix_a = np.random.randn(size, size)
np_matrix_b = np.random.randn(size, size)
tf_matrix_a = tf.random.normal((size, size))
tf_matrix_b = tf.random.normal((size, size))

# Benchmark NumPy
start_time = time.time()
np_result = np.dot(np_matrix_a, np_matrix_b)
np_duration = time.time() - start_time

# Benchmark TensorFlow on CPU
start_time = time.time()
tf_result = tf.matmul(tf_matrix_a, tf_matrix_b)
tf_duration = time.time() - start_time

print("NumPy Duration: {:.6f} seconds".format(np_duration))
print("TensorFlow (CPU) Duration: {:.6f} seconds".format(tf_duration))


In [40]:

# Example forward propagation in Python
def forward_propagation(X, W, b):
    Z = np.dot(W, X) + b  # Weighted sum
    A = 1 / (1 + np.exp(-Z))  # Sigmoid activation function
    return A

# Dummy data
X = np.array([[1.0], [2.0], [3.0]])  # Input
W = np.array([[0.2, 0.4, 0.6]])  # Weights
b = np.array([[0.5]])  # Bias

# Forward propagation
output = forward_propagation(X, W, b)
print("Output of forward propagation:", output)


Output of forward propagation: [[0.96442881]]


In [48]:
import numpy as np

# Sigmoid activation function
def sigmoid(x):
    return 1/1+np.exp(-x)

# ReLU activation function
def relu(x):
    return np.maximum(0, x) 

# Tanh activation function
def tanh(x):
    return np.tanh(x)

# Example of activation functions
x = np.array([-1.0, 0.0, 1.0, 2.0])
print("Sigmoid:", sigmoid(x))
print("ReLU:", relu(x))
print("Tanh:", tanh(x))


Sigmoid: [3.71828183 2.         1.36787944 1.13533528]
ReLU: [0. 0. 1. 2.]
Tanh: [-0.76159416  0.          0.76159416  0.96402758]


In [ ]:
def forward_with_activation(X, W, b, activation_function):
    Z = np.dot(W, X) + b  # Weighted sum
    match activation_function:
        case 'sigmoid': 
            A = sigmoid(Z)
        case 'relu' : 
            A = relu(Z)
        case 'tanh' :
            A = tanh(Z)
    return A

# Testing the function
W = np.array([[0.2, 0.4, 0.6]])
b = np.array([[0.5]])
X = np.array([[1.0], [2.0], [3.0]])

output = forward_with_activation(X, W, b, activation_function='relu')
print("Output with ReLU activation:", output)
